apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: usermicroservice
spec:
  replicas: 2
  template:
    metadata:
      labels:
        app: usermicroservice
    spec:
      containers:
      - image: d3334/userms:7
        name: usermicroservice
        resources:
          limits:
            memory: "256Mi"
            cpu: "200m"
        imagePullPolicy: Always
        ports:
        - name: user-port
          containerPort: 8080
status: {}
